version: '3'
    
services:

  db:
    image: "postgres"
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - internal
    environment:
      POSTGRES_DB: aletheia

  app:
    build: .
    restart: always
    networks:
      - internal
    expose:
      - "8000"

    environment:
      ROCKET_DATABASES: "{postgres={url=\"postgres://postgres:${POSTGRES_PASSWORD}@db/aletheia\"}}"
      SECRET_KEY: "${SECRET_KEY}"
      SALT_LENGTH: "${SALT_LENGTH}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      BUCKET_NAME: "${BUCKET_NAME}"
      AWS_REGION: "${AWS_REGION}"

volumes:
  data:

networks:
  internal:
    external: false
